@url_dev = http://localhost:3052/v1/api/

### Sign-Up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: a5b4c273b37db06345a93fd38aa21c4d11c5f4e632cbc3426e9bf5b4e6124acc72f4be591cb3018a827d86fa4957cd53f2e9da8527d4b7daeebf36d4aefe449f

{
    "name": "dhuu",
    "email": "ddhuu@gmail.com",
    "password": "123"
}
